application: nmlorgdev
module: movies
version: 1
runtime: python27
api_version: 1
default_expiration: 0
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /js/
  static_dir: js

- url: /.*
  script: main.app

inbound_services:
- warmup
